---
dependencies:
   - { role: boto }
   - { role: pip-devel }

galaxy_info:
  author: chris.cundill
  description: Installs Ansible CLI tools.
  company: Driver and Vehicle Licensing Agency (DVLA)
  license: license (MIT)
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - ansible
    - ansible-cli