- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run Ansible Galaxy to install roles
      local_action: command ansible-galaxy install --force -r requirements.yml -p roles-external
