---
- name: deploy crt
  template: src=server.crt dest=/etc/nginx/ssl/server.crt
  notify: restart nginx
  tags:
    - nginx

- name: deploy key
  template: src=server.key dest=/etc/nginx/ssl/server.key
  notify: restart nginx
  tags:
    - nginx

- name: deploy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/conf.d/{{nginx_https_front_upstream.nginx_conf_name}}.conf
  notify: restart nginx
  tags:
    - nginx
