---
- name: Add MongoDB repository
  yum_repository:
    name: mongodb
    description: Mongodb repo
    baseurl: https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.4/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    enabled: yes

- name: Install MongoDB
  mongodb_install:
    yum: name=mongodb-org state=installed

- name: Copy the configuration file template to the remote host
  template:
    force: yes
    src: mongod.j2
    dest: /etc/mongod.conf

- name: Start the mongo daemon
  service: name=mongod state=restarted
