---
- name: Add Route 53 Record Set
  route53:
    command: create
    overwrite: yes
    hosted_zone_id: "{{platform_route53.zones[deploy_env].zone_id}}"
    zone: "{{deploy_env}}.{{domain}}"
    private_zone: yes
    record: "{{ec2_prefix}}.{{deploy_env}}.{{domain}}"
    value: "{{route53_add_recordset_value}}"
    type: "{{ route53_add_recordset_type }}"
    ttl: 300
    wait: yes
    aws_access_key: "{{sts_assumed_role.sts_creds.access_key if sts_assumed_role is defined else omit}}"
    aws_secret_key: "{{sts_assumed_role.sts_creds.secret_key if sts_assumed_role is defined else omit}}"
    security_token: "{{sts_assumed_role.sts_creds.session_token if sts_assumed_role is defined else omit}}"
  tags:
    - route53-add