#!/bin/bash

set -o nounset

readonly TARGET_DIR="$(dirname ${BASH_SOURCE[0]})/jobs"

[[ -d $TARGET_DIR ]] || mkdir $TARGET_DIR || { echo "Failed to create the target $TARGET_DIR"; exit 1; }
rm -f $TARGET_DIR/*

for curr_job in $(sudo ls -1 ~jenkins/jobs); do 
  sudo cp ~jenkins/jobs/$curr_job/config.xml $TARGET_DIR/$curr_job; 
done
sudo chown ec2-user:ec2-user $TARGET_DIR/*
