#!/bin/bash

set -o nounset

readonly TARGET_DIR="$(dirname ${BASH_SOURCE[0]})/configs"

[[ -d $TARGET_DIR ]] || mkdir $TARGET_DIR || { echo "Failed to create the target $TARGET_DIR"; exit 1; }
rm -f $TARGET_DIR/*
sudo cp ~jenkins/*.xml $TARGET_DIR
sudo chown ec2-user:ec2-user $TARGET_DIR/*
